/rat/db/set DETECTOR geo_file "geo/alphacounter.geo"
/run/initialize
/rat/proc count
/rat/procset update 10
/rat/proc outroot
/rat/procset file "alpha.root"

/generator/add multicombo gun:fill:poisson
/generator/vtx/set neutron 0 0 0 6.003|counter_region|1
/generator/vtx/set neutron 0 0 0 7.687|counter_region|1
/generator/vtx/set neutron 0 0 0 5.305|counter_region|1
/generator/rate/set 1

/run/beamOn 1000
exit
